"""Exclude known autogenerated forum-summary and navigation artifacts."""
import re
from urllib.parse import urlparse
from continuation_quality import reject_reason as base_reject

VERSION = '20260911-math-artifacts-v3'


def reject_reason(source, identifier, text, tokens):
    reason = base_reject(source,identifier,text,tokens)
    if reason:
        return reason
    host = urlparse(identifier).hostname or ''
    if host.endswith('physicsforums.com') and 'in summary' in text[:1500].lower():
        return 'forum_autosummary'
    if re.search(r'^#?\s*(?:month:|search by topic|resources tagged with)',text[:300],re.I|re.M):
        return 'math_navigation_archive'
    if re.search(r'\blet be a (?:curve|function) in\s*\.',text,re.I):
        return 'missing_mathematical_notation'
    return None
